#pragma once

//Vertax_INFO
#define VERTEXT_POSITION						0x0001
#define VERTEXT_COLOR							0x0002
#define VERTEXT_NORMAL							0x0004
#define VERTEXT_TANGENT						0x0008
#define VERTEXT_TEXTURE_COORD0			0x0010
#define VERTEXT_TEXTURE_COORD1			0x0020

#define VERTEXT_BONE_INDEX_WEIGHT		0x1000

//VertaxTexture_INFO
#define VERTEXT_TEXTURE					(VERTEXT_POSITION | VERTEXT_TEXTURE_COORD0)
#define VERTEXT_DETAIL					(VERTEXT_POSITION | VERTEXT_TEXTURE_COORD0 | VERTEXT_TEXTURE_COORD1)
#define VERTEXT_NORMAL_TEXTURE			(VERTEXT_POSITION | VERTEXT_NORMAL | VERTEXT_TEXTURE_COORD0)
#define VERTEXT_NORMAL_TANGENT_TEXTURE	(VERTEXT_POSITION | VERTEXT_NORMAL | VERTEXT_TANGENT | VERTEXT_TEXTURE_COORD0)
#define VERTEXT_NORMAL_DETAIL			(VERTEXT_POSITION | VERTEXT_NORMAL | VERTEXT_TEXTURE_COORD0 | VERTEXT_TEXTURE_COORD1)
#define VERTEXT_NORMAL_TANGENT__DETAIL	(VERTEXT_POSITION | VERTEXT_NORMAL | VERTEXT_TANGENT | VERTEXT_TEXTURE_COORD0 | VERTEXT_TEXTURE_COORD1)

//ObjectMoving
#define DIR_FORWARD								0x01
#define DIR_BACKWARD								0x02
#define DIR_LEFT										0x04
#define DIR_RIGHT									0x08
#define DIR_UP											0x10
#define DIR_DOWN									0x20

//TextureType
#define RESOURCE_TEXTURE2D					0x01
#define RESOURCE_TEXTURE2D_ARRAY		0x02	//[]
#define RESOURCE_TEXTURE2DARRAY		0x03
#define RESOURCE_TEXTURE_CUBE			0x04
#define RESOURCE_BUFFER						0x05

//Marterial_INFO
#define MATERIAL_ALBEDO_MAP			0x01
#define MATERIAL_SPECULAR_MAP		0x02
#define MATERIAL_NORMAL_MAP			0x04
#define MATERIAL_METALLIC_MAP		0x08
#define MATERIAL_EMISSION_MAP		0x10
#define MATERIAL_DETAIL_ALBEDO_MAP	0x20
#define MATERIAL_DETAIL_NORMAL_MAP	0x40

//AnimationOperatingType
//#define _WITH_ANIMATION_SRT
#define _WITH_ANIMATION_INTERPOLATION

//AnimationType
#define ANIMATION_TYPE_ONCE			0
#define ANIMATION_TYPE_LOOP			1
#define ANIMATION_TYPE_PINGPONG		2

//AnimationCallBackEpsilon
#define ANIMATION_CALLBACK_EPSILON	0.015f

//NumOfBones
#define SKINNED_ANIMATION_BONES		128

//Camera_INfO
#define ASPECT_RATIO				(float(FRAME_BUFFER_WIDTH) / float(FRAME_BUFFER_HEIGHT))
#define FIRST_PERSON_CAMERA			0x01
#define SPACESHIP_CAMERA					0x02
#define THIRD_PERSON_CAMERA			0x03

#define D3DCOMPILE_DEBUG 1

//Blur Switch
#define BLUR_OFF 0 
#define BLUR_ON 1 

//BehaviorTool
#define BHAVIOR_TOOL_MODE